"""empty message

Revision ID: 487e5cae7994
Revises: 2807edd385a2
Create Date: 2021-12-01 10:32:41.588545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487e5cae7994'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
